# Generated by Django 4.2.6 on 2023-10-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_death',
            new_name='died',
        ),
    ]
